drone_num: 12

waypoint_num: 1

waypoints:
  - waypoint_id: 0
    position:
      x: 14.0
      y: 0.0
      z: 1.2
    yaw: 0.0

swarm_matrix:
  swarm_yaw: 0.0
  drones:
  - drone_id: 0
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    yaw: 0.0
  - drone_id: 1
    position:
      x: 0.0
      y: 4.0
      z: 0.0
    yaw: 0.0
  - drone_id: 2
    position:
      x: 0.0
      y: 7.0
      z: 0.0
    yaw: 0.0
  - drone_id: 3
    position:
      x: 0.0
      y: 17.0
      z: 0.0
    yaw: 0.0
  - drone_id: 4
    position:
      x: 0.0
      y: 13.0
      z: 0.0
    yaw: 0.0
  - drone_id: 5
    position:
      x: 0.0
      y: 10.0
      z: 0.0
    yaw: 0.0
    ## broken
  - drone_id: 6
    position:
      x: 0.0 #-(14-y)+2+1
      y: 0.0  #8+x/2-2-1
      z: 0.0
    yaw: 0.0
    ## 2nd line 3rd drone
  - drone_id: 7
    position:
      x: -7.5 #-(14-y-x)-2
      y: 18.0 #8+x/2-2
      z: 0.0
    yaw: 0.0
    
    ## 2rd drone
    ## 2nd line 4th drone
  - drone_id: 8
    position:
      x: -4.5 #-(14-y-x)-2
      y: 6.5 #8-x/2+2
      z: 0.0
    yaw: 0.0

    ## 2nd line 1rd drone
  - drone_id: 9
    position:
      x: -4.5
      y: 11.0
      z: 0.0
    yaw: 0.0
    
    ## broken
  - drone_id: 10
    position:
      x: 0.0 #-(14-y)+2
      y: 0.0 #8-x/2+2
      z: 0.0
    yaw: 0.0
    ## 2nd line 2nd drone
  - drone_id: 11
    position:
      x: -9.0
      y: 7.00
      z: 0.0
    yaw: 0.0