drone_num: 4

waypoint_num: 1

waypoints:
  - waypoint_id: 0
    position:
      x: 2.0
      y: 0.0
      z: 1.2
    yaw: 0.0

swarm_matrix:
  swarm_yaw: 0.0
  drones:
  - drone_id: 0
    position:
      x: 0.0
      y: 2.0
      z: 0.0
    yaw: 0.0
  - drone_id: 1
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    yaw: 0.0
  - drone_id: 2
    position:
      x: 15.5
      y: 2.0
      z: 0.0
    yaw: 0.0
  - drone_id: 3
    position:
      x: 15.5
      y: 0.0
      z: 0.0
    yaw: 0.0