drone_num: 1

waypoint_num: 1

waypoints:
  - waypoint_id: 0
    position:
      x: 9.0
      y: 1.0
      z: 1.2
    yaw: 0.0

swarm_matrix:
  swarm_yaw: 0.0
  drones:
  - drone_id: 0
    position:
      x: 0.0
      y: 6.0
      z: 0.0
    yaw: 0.0
  - drone_id: 1
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    yaw: 0.0
