drone_num: 2

waypoint_num: 1

waypoints:
  - waypoint_id: 0
    position:
      x: 3.0
      y: 0.0
      z: 1.2
    yaw: 0.0

swarm_matrix:
  swarm_yaw: 0.0
  drones:

  - drone_id: 3
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    yaw: 0.0
