drone_num: 1

waypoint_num: 4

waypoints:
  - waypoint_id: 0
    position:
      x: 30.0
      y: 0.0
      z: 1.2
    yaw: 0.0

  - waypoint_id: 1
    position:
      x: 30.0
      y: 20.0
      z: 1.2
    yaw: 0.0

  - waypoint_id: 2
    position:
      x: 0.0
      y: 20.0
      z: 1.2
    yaw: 0.0

  - waypoint_id: 3
    position:
      x: 0.0
      y: 0.0
      z: 1.2
    yaw: 0.0

swarm_matrix:
  swarm_yaw: 0.0
  drones:
  - drone_id: 0
    position:
      x: 0.0
      y: 0.0
      z: 0.0
    yaw: 0.0
